name: Build and Deploy Spatial AI Map to `deploy` branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare deployment directory
        run: |
          mkdir deploy
          cp spatial_ai_map_sample.csv deploy/
          sed "s|__MAPBOX_TOKEN__|${{ secrets.MAPBOX_TOKEN }}|g" index.template.html > deploy/index.html

      - name: Deploy to `deploy` branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: deploy
